apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-merra-plot
  labels:
    app: orion-merra-plot
spec:
  selector:
    matchLabels:
      app: orion-merra-plot
  template:
    metadata:
      labels:
        app: orion-merra-plot
    spec:
      containers:
      - name: orion-merra-plot
        image: anbadrin/orion-project3:merra-plot
        imagePullPolicy: Always
        ports:
        - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: orion-merra-plot
  labels:
    app: orion-merra-plot
spec:
  selector:
    app: orion-merra-plot
  type: NodePort
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
