apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orionrabbit
spec:
  replicas: 1
  serviceName: orionrabbit
  selector:
    matchLabels:
      app: orionrabbit
  template:
    metadata:
      labels:
        app: orionrabbit
    spec:
      containers:
      - name: orionrabbit
        image: rabbitmq:3-management
        env:
        - name: "RABBITMQ_ERLANG_COOKIE"
          value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
            type: DirectoryOrCreate