version: 2.1
orbs:
  node: circleci/node@4.7.0
  docker: circleci/docker@0.5.13
jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
workflows:
  on_commit:
    jobs:
      - build_and_test
      - docker/publish:
          image: anbadrin/orion-assignment1:ui
          dockerfile: Dockerfile
          requires:
            - build_and_test